docs/deploy.md

@nickbradley I made these edits while I was going through the instructions, in case they are useful for others. I'd appreciate a review as I'm not 100% confident.

Deploy guide edits

---

packages/grader/src/task/GradeTask.ts

Logging updates

---

docker-compose.yml

Pass --quiet flag to mongod

---

.env.sample
docker-compose.yml
packages/common/Log.ts
packages/grader/src/git/Repository.ts
yarn.lock

See #123.
@rtholmes you can let me know if you want to do this a different way (common/Log.ts). This was easiest.

Configure LOG_LEVEL env var

---

packages/autotest/src/autotest/ClassPortal.ts
packages/autotest/src/autotest/mocks/MockClassPortal.ts
packages/autotest/src/github/GitHubAutoTest.ts

Test: https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T1/d0_r5t0b/commit/6cfd47be38b320c741b0613f2d0f7d958e35f2c6

Use the container config custom feedbackMode field to the right feedback

---

docs/deploy.md

Add cron job script and description for archiving old runs

---

packages/portal/backend/src/controllers/CourseController.ts
packages/portal/backend/src/server/common/AdminRoutes.ts
packages/portal/backend/test/controllers/CourseControllerSpec.ts
packages/portal/backend/test/server/AdminRoutesSpec.ts

Without number of records limit found in /portal/admin/dashboard #144

Add a /portal/admin/dashboard_all endpoint

---

packages/grader/src/storage/Workspace.ts
packages/grader/src/task/GradeTask.ts

Closes #174.
(Haven't tested this but it was a pretty simple change...)

Clear the workspace directory if it exists from a previous run

---

packages/portal/backend/src/controllers/AdminController.ts
packages/portal/backend/src/controllers/PersonController.ts
packages/portal/backend/src/server/common/AdminRoutes.ts
packages/portal/backend/test/controllers/AdminControllerSpec.ts

The evolution of this change will happen here. Before this will work we need to update how we handle withdrawn students, and then the provisioning can follow.

see #216 update withdrawn handling

---

packages/autotest/test/ClassPortalSpec.ts
packages/portal/backend/src/Factory.ts
packages/portal/backend/src/controllers/AdminController.ts
packages/portal/backend/src/controllers/AuthController.ts
packages/portal/backend/src/controllers/CourseController.ts
packages/portal/backend/src/controllers/DatabaseController.ts
packages/portal/backend/src/controllers/GitHubActions.ts
packages/portal/backend/src/controllers/GitHubController.ts
packages/portal/backend/src/controllers/RepositoryController.ts
packages/portal/backend/src/server/BackendServer.ts
packages/portal/backend/src/server/common/AdminRoutes.ts
packages/portal/backend/src/server/common/AutoTestRoutes.ts
packages/portal/backend/test/TestHarness.ts
packages/portal/backend/test/controllers/AdminControllerSpec.ts
packages/portal/backend/test/controllers/AuthControllerSpec.ts
packages/portal/backend/test/controllers/CourseControllerSpec.ts
packages/portal/backend/test/controllers/DatabaseControllerSpec.ts
packages/portal/backend/test/controllers/GitHubActionSpec.ts
packages/portal/backend/test/controllers/GitHubControllerSpec.ts
packages/portal/backend/test/controllers/RepositoryControllerSpec.ts
packages/portal/backend/test/controllers/TeamControllerSpec.ts
packages/portal/backend/test/server/AdminRoutesSpec.ts
packages/portal/backend/test/server/AutoTestRoutesSpec.ts
packages/portal/frontend/src/app/views/AdminConfigTab.ts

see #194. This will be in a PR since it will probably break tests a bunch of times but should not significantly change product code.

Revisit missing testcases

---

packages/portal/frontend/src/app/views/StudentView.ts

(cherry picked from commit 3e97a3afe0c4786b64892c936338aad517dfaacb)
Allows sub-classes of `StudentView` to access originally private fields (like `grades`)

Extend access to StudentView variables

---

docs/deploy.md

This avoids the issue reported in #225.
Closes #225.

Write certbot output to log

---

packages/portal/backend/src/server/common/CSVParser.ts

From here on, every integration will be using CWL.

update githubId from csId to CWL

---

package.json

Fixes Docker container build issue.

Upgraded TypeScript version

---

docs/deploy.md
packages/portal/backend/package.json
packages/portal/backend/src/server/common/CSVParser.ts
packages/portal/backend/test/CSVParserSpec.ts
packages/portal/backend/test/data/classlistDuplicateField.csv
packages/portal/backend/test/data/classlistEmptyField.csv
packages/portal/frontend/html/admin.html

New feature: check for blanks and duplicates of CWL and CSID in csv imports.
Documentation: deploy overhaul
Bug fix: make coverage command work

Updates from CPSC tech

---

.vscode/launch.json
packages/portal/frontend/html/index.html

Minor, will merge without review.
(Onsen version discussed a month ago is still a problem, so we'll pin it.)

VSCode config + onsen version pin

---

packages/portal/backend/test/controllers/GitHubControllerSpec.ts

- Issue fixes very minor bug causing CircleCI tests to fail.
- Waiting for CircleCI tests to pass before merging.
- CI Tests pass in development environment.

Switched repository that is cloned

---

docs/developer/bootstrap.md
docs/developer/continuousintegration.md
docs/instructor/portal.md
docs/tech-staff/architecture.md
docs/tech-staff/forkcustomization.md
docs/tech-staff/hardware.md

- General improvements to copy and formatting
- Fixing broken links

Documentation Changes

---

docs/instructor/gettingstarted.md

Fixed typo in path to environment configuration docs

Fixed typo

---

.circleci/config.yml
packages/portal/backend/src/server/common/CSVParser.ts

- We started to receive an error while compiling Classy during our nightly build, even though our code had not previously changed. A dependency must have changed, but we changed our code to explicitly declare the error type here. In other sections of our code, we are not forced to explicitly declare the error type at this time.

Fixing compilation issue

---

packages/portal/backend/src/server/common/CSVParser.ts
packages/portal/frontend/src/app/views/AdminConfigTab.ts

- Comments out code that was failing since it could not find the HTML block removed to comment out the feature.
- Fixes fix with BOM at the beginning of some CSV documents.

BOM Fix and PR Removal Fix

---

packages/portal/backend/src/controllers/GitHubActions.ts
packages/portal/backend/src/controllers/GitHubController.ts

Particularly useful for our grading scripts which will be migrated to the classy plugin when this is merged. Earliest seen here: https://github.com/ubccpsc310/classy/pull/80 though never merged as it may need some cleanup

Add ability for classy to add an issue to a repo

---

packages/portal/backend/src/controllers/AdminController.ts

Very minor code change from https://github.com/ubccpsc310/classy/pull/80

Fetch teams concurrently when performing a repo provision

---

packages/common/types/PortalTypes.ts
packages/portal/backend/src/controllers/AdminController.ts
packages/portal/backend/src/controllers/CourseController.ts

This _will_ break the 310 classy-plugin
requires https://github.com/ubccpsc310/classy-plugin/pull/8

Remove forwardCustomFields

---

packages/portal/backend/src/server/common/AdminRoutes.ts
packages/portal/backend/test/server/AdminRoutesSpec.ts

resolves #416 
No idea if that test is right

De-attach GitHub on teams when repo is deleted

---

docker-compose.yml

remove version from docker compose
